name: CI-SV
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split Scriptable Variables package
      run: |
        git branch -d $UPM_BRANCH &> /dev/null || echo $UPM_BRANCH branch not found
        git subtree $UPM_BRANCH -P "$PKG_ROOT" -b $UPM_BRANCH
        git checkout $UPM_BRANCH
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "Fix samples folder"
        fi
        git push -f -u origin $UPM_BRANCH
      env:
        UPM_BRANCH: upm-SV
        PKG_ROOT: Assets/ScriptableVariables
